disabled_rules: # rule identifiers to exclude from running
  - multiple_closures_with_trailing_closure
  - variable_name
  - trailing_whitespace
  - line_length
  - valid_docs
  - function_parameter_count
  - cyclomatic_complexity
  - file_length
  - function_body_length

type_body_length:
  - 300 # warning
  - 400 # error

opt_in_rules:
  - empty_count
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - empty_parameters
  - explicit_init
  - nesting
  - object_literal
  - opening_brace
  - operator_whitespace
  - private_action
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - yoda_condition

excluded:
  - Pods
  - Jinko/Libraries/UIImageEffects.swift
  - JinkoTests/*
  - R.generated.swift
